"""Add FilingHistory table

Revision ID: a8d2fbd0b517
Revises: dea577fbf5c8
Create Date: 2025-04-30 23:45:20.484722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8d2fbd0b517'
down_revision = 'dea577fbf5c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FilingHistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usdotNumber', sa.String(length=100), nullable=False),
    sa.Column('carrierEmail', sa.String(length=255), nullable=False),
    sa.Column('carrierMileage', sa.String(length=100), nullable=True),
    sa.Column('carrierEin', sa.String(length=100), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('filingPath', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FilingHistory')
    # ### end Alembic commands ###
