"""add isAdmin and lastLogin column to User table

Revision ID: b8c74986f83f
Revises: 2799efc7eadb
Create Date: 2025-04-21 21:28:42.318854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8c74986f83f'
down_revision = '2799efc7eadb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isAdmin', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('lastLogin', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('lastLogin')
        batch_op.drop_column('isAdmin')

    # ### end Alembic commands ###
