"""update updated_at column in user table and add status column

Revision ID: dea577fbf5c8
Revises: b8c74986f83f
Create Date: 2025-04-22 12:49:06.721990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dea577fbf5c8'
down_revision = 'b8c74986f83f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=True))
        batch_op.alter_column('updated_at',
            existing_type=sa.DateTime(),
            existing_nullable=False,
            existing_default=sa.func.now(),  # Update if necessary
            nullable=False,
            default=sa.func.now())

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
